/* MADE BY SIMBA ON 1/19/2017 This is free software
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

#include <iostream>

using namespace std;

int main()
{
  int sum = 0; // we will initialize a variable to hold the sum
  int x = 1;
  int y = 2;  // as well as two more variables to hold the values of the Fibonacci sequence
  int z = 2; //I lied we will need a third value to hold the temporary value of x while we are calculating
  while (x < 4000000) // while x is less than four million
  {

      if (!(z%2))
        sum += z;



    x += y;  // emulate the Fibonacci sequence
    y = z;
    z = x;

  }
  cout << sum;
  cin.get();
  return 0;
}
