/* CREATED BY SIMBA ON 1-23-2017 THIS IS FREE SOFTWARE
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55
What is the value of the first triangle number to have over five hundred divisors?
*/
// go me
#include <iostream>

using namespace std;

int main()
{
    int N = 0, n, a, divisors, d1;
    int power = 0;


    for (int x = 1; x <100000; x++ )
    {
        N += x;
        n = N;
        divisors = 0;
    while (!(n % 2))
    {
        power ++;
        n /= 2;
    }
    if (power > 0)
        divisors ++;
      while (power > 0)
      {
          divisors ++;
          power --;
      }

      power = 0;
      for (a = 3; a <= n; a += 2)
      {
          d1 = 0;
          if (!(n % a))
          do
          {
              power ++;
              n /= a;
          } while (!(n%a));
        if (power > 0)
            d1 ++;
        while (power > 0)
            {
               d1 ++;
               power --;
            }

        if (d1 > 0)
            if (divisors > 0)
                divisors *= d1;
            else
                divisors = d1;
        power = 0;
      }

        if (divisors > 500)
        {
                cout << N << " has " << divisors << " divisors it is the " << x << "th triangle number" <<  endl;
                break;
        }

    }

}
